// 3 大题材一键开箱预制世界观 Demo 数据包

import type { CodexEntity } from '../types'

// 演示数据固定时间戳：避免 DEMO_TS/Math.random 不确定性，保证可测与稳定 React key。
const DEMO_TS = 1700000000000

export interface WorldviewDemoPack {
  id: string
  title: string
  subtitle: string
  genre: 'xianxia' | 'cyberpunk' | 'fantasy'
  badge: string
  description: string
  entitiesCount: number
  entities: (projectId: string) => CodexEntity[]
}

export const WORLDVIEW_DEMO_PACKS: WorldviewDemoPack[] = [
  // ── 1. 经典东方修仙世界观 ────────────────────────────────
  {
    id: 'cultivation-classic',
    title: '九霄问仙录 (东方修仙)',
    subtitle: '完整修真宗门·神兵法宝·境界战力·爱恨因果图谱',
    genre: 'xianxia',
    badge: '玄幻修仙',
    description: '包含主角陈渊、宗门大弟子萧景行、青岚剑宗、九幽魔门、青铜古塔、云州断界渊等 8 大实体与双向关系网。',
    entitiesCount: 8,
    entities: (projectId: string): CodexEntity[] => [
      {
        id: `demo-c1-${DEMO_TS}`,
        projectId,
        name: '陈渊',
        aliases: ['渊哥', '废脉少主', '吞天神体'],
        category: 'character',
        attributes: { 身份定位: '青岚宗杂役弟子(实为神体传承者)', 实力境界: '淬体九重巅峰', 保密等级: '绝密' },
        relations: [
          { targetId: '萧景行', targetName: '萧景行', relationType: '宿敌', description: '多次暗中打压' },
          { targetId: '青岚宗', targetName: '青岚宗', relationType: '所属宗门', description: '杂役院' },
          { targetId: '青铜小塔', targetName: '青铜小塔', relationType: '持有至宝', description: '识海温养' },
        ],
        summary: '废脉觉醒吞天神体的男主，行事果决沉稳，不信天命，深藏不露。',
        detailMarkdown: `### 人物背景\n本为陈家少主，因灵脉破碎沦为青岚宗杂役，机缘巧合在断界渊唤醒青铜古塔。\n\n### 功法与神通\n《吞天造化诀》：可炼化诸天异火与煞气。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-c2-${DEMO_TS}`,
        projectId,
        name: '萧景行',
        aliases: ['内门大师兄', '景行师兄', '青岚双骄'],
        category: 'character',
        attributes: { 身份定位: '青岚宗内门首席真传', 实力境界: '筑基初期', 保密等级: '公开' },
        relations: [
          { targetId: '陈渊', targetName: '陈渊', relationType: '打压目标', description: '夺其家传玉佩' },
          { targetId: '青岚宗', targetName: '青岚宗', relationType: '核心真传' },
        ],
        summary: '青岚宗天之骄子，表面温润如玉风度翩翩，实则心胸狭隘，容不得他人超越。',
        detailMarkdown: `### 人物背景\n青岚宗大长老之义子，剑道天赋绝伦，视宗门掌教之位为囊中之物。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-c3-${DEMO_TS}`,
        projectId,
        name: '洛青璇',
        aliases: ['青璇仙子', '太上关门弟子'],
        category: 'character',
        attributes: { 身份定位: '太上长老关门弟子/太阴神体', 实力境界: '筑基中期', 保密等级: '核心机密' },
        relations: [
          { targetId: '陈渊', targetName: '陈渊', relationType: '暗中盟友', description: '受其救命之恩' },
          { targetId: '青岚宗', targetName: '青岚宗', relationType: '圣女候补' },
        ],
        summary: '清冷出尘的剑道天才，性格淡漠不染尘埃，唯独对陈渊持有特殊的探究与信任。',
        detailMarkdown: `### 核心设定\n身负太阴之气，需借纯阳天火调和，与陈渊的混沌灵气产生宿命共鸣。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-f1-${DEMO_TS}`,
        projectId,
        name: '青岚宗',
        aliases: ['青岚剑派', '云州三大正道'],
        category: 'faction',
        attributes: { 宗门品阶: '二流巅峰', 镇派功法: '《青岚太虚剑诀》', 宗门属地: '云州苍霞山脉' },
        relations: [
          { targetId: '断界渊', targetName: '断界渊', relationType: '封锁禁地' },
          { targetId: '九幽魔宫', targetName: '九幽魔宫', relationType: '世代死仇' },
        ],
        summary: '云州边陲传承千年的正道巨擘，以太虚剑阵与清灵剑气名震南岭。',
        detailMarkdown: `### 宗门格局\n分为天剑峰、地灵峰、药王谷、杂役院四大分脉，内部派系倾轧严重。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-f2-${DEMO_TS}`,
        projectId,
        name: '九幽魔宫',
        aliases: ['九幽煞宗', '魔道魁首'],
        category: 'faction',
        attributes: { 宗门品阶: '一流魔门', 镇教至宝: '九幽招魂幡', 危险等级: '极度凶险' },
        relations: [
          { targetId: '青岚宗', targetName: '青岚宗', relationType: '图谋覆灭' },
        ],
        summary: '南疆凶名赫赫的魔道第一宗，行事狠辣不择手段，常年觊觎断界渊下的太古遗迹。',
        detailMarkdown: `### 核心秘法\n以九幽地煞祭炼魔兵，门徒遍布各州散修盟会。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-i1-${DEMO_TS}`,
        projectId,
        name: '青铜小塔',
        aliases: ['混沌镇天塔', '太古铜塔'],
        category: 'item',
        attributes: { 法宝品阶: '天阶极品(封印中)', 当前层数: '九层已开第一层', 核心效能: '时间加速·混沌熔炉' },
        relations: [
          { targetId: '陈渊', targetName: '陈渊', relationType: '认主绑定' },
        ],
        summary: '太古遗留的至高神器，内蕴一方独立混沌小天地，可十倍加速参悟功法。',
        detailMarkdown: `### 神通能力\n第一层【混沌熔炉】：可自动提纯任何劣质丹药与斑驳灵气。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-l1-${DEMO_TS}`,
        projectId,
        name: '断界渊',
        aliases: ['万丈魔渊', '太古坠魔地'],
        category: 'location',
        attributes: { 危险等级: '禁地特级', 地理位置: '青岚宗后山十万里外', 核心产出: '太阴玄煞/天外陨铁' },
        relations: [
          { targetId: '青岚宗', targetName: '青岚宗', relationType: '宗门后山禁地' },
        ],
        summary: '云州与魔域交界处的天堑深渊，终年黑雾笼罩，藏有太古仙魔大战的诸多秘境遗迹。',
        detailMarkdown: `### 区域环境\n深渊下罡风如刀，寻常金丹修士难逾千丈。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-t1-${DEMO_TS}`,
        projectId,
        name: '九品金丹',
        aliases: ['极品天丹', '九转金丹'],
        category: 'term',
        attributes: { 境界层级: '金丹境核心标准', 极品品阶: '九纹至尊丹' },
        relations: [],
        summary: '金丹大道之基，一品最低，九品为尊。凝练九品金丹者，方有一窥真仙大道的机缘。',
        detailMarkdown: `### 规则定义\n唯有在筑基期熔铸无暇道基并渡过九重紫霄神雷者方能成就。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
    ],
  },

  // ── 2. 赛博朋克与科幻世界观 ──────────────────────────────
  {
    id: 'cyberpunk-2077',
    title: '夜幕霓虹 (赛博朋克)',
    subtitle: '巨型财阀·义体改造·暗网协议·边缘行者',
    genre: 'cyberpunk',
    badge: '赛博朋克',
    description: '包含传奇雇佣兵 V、荒坂巨型财阀、军用科技、黑客深网、斯安威斯坦神经义体等实体与博弈网络。',
    entitiesCount: 6,
    entities: (projectId: string): CodexEntity[] => [
      {
        id: `demo-cy-1-${DEMO_TS}`,
        projectId,
        name: 'V',
        aliases: ['边缘行者V', '夜之城传奇'],
        category: 'character',
        attributes: { 身份定位: '顶级雇佣兵/独狼', 义体化率: '65%', 神经系统: '军用级斯安威斯坦5代' },
        relations: [
          { targetId: '荒坂集团', targetName: '荒坂集团', relationType: '生死对抗' },
          { targetId: '强尼·银手', targetName: '强尼·银手', relationType: '意识共生' },
        ],
        summary: '夜之城最声名显赫的王牌雇佣兵，身怀顶级黑客与战斗义体，游走在巨型企业夹缝之中。',
        detailMarkdown: `### 核心背景\n为了在残酷的夜之城留下不朽传说，赌上生命挑战荒坂财阀的统治。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-cy-2-${DEMO_TS}`,
        projectId,
        name: '荒坂集团',
        aliases: ['荒坂公司', 'Arasaka Corp'],
        category: 'faction',
        attributes: { 企业评级: '超级巨头(Megacorp)', 垄断领域: '安保/武器/意识上传Relic', 控制权: '荒坂家族' },
        relations: [
          { targetId: '新夜城', targetName: '新夜城', relationType: '幕后统治者' },
        ],
        summary: '掌控全球军火与意识上传技术的巨型企业，夜之城的绝对幕后主宰。',
        detailMarkdown: `### 权力结构\n由荒坂三郎一手缔造，拥有令主权国家俯首的私有浮空舰队与精锐机械军团。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-cy-3-${DEMO_TS}`,
        projectId,
        name: '斯安威斯坦',
        aliases: ['军用级沙盘', '时空加速神经阀'],
        category: 'item',
        attributes: { 义体类别: '中枢操作系统', 反应加成: '思维感知加速500%', 负荷指数: '极易导致赛博精神病' },
        relations: [
          { targetId: 'V', targetName: 'V', relationType: '脊柱植入' },
        ],
        summary: '军方绝密研发的高负荷神经操作系统，启动后可将使用者体感时间压缩至子弹时间。',
        detailMarkdown: `### 性能指标\n需搭配高纯度免疫抑制剂使用，连续过载会导致中枢神经崩溃。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-cy-4-${DEMO_TS}`,
        projectId,
        name: '新夜城',
        aliases: ['罪恶之都', 'Night City'],
        category: 'location',
        attributes: { 城市规模: '超大型独立自治城邦', 贫富差距: '极度悬殊', 安全评级: '黑区高危' },
        relations: [],
        summary: '高耸入云的企业摩天楼与遍布有毒废水的下层贫民窟交织的未来赛博巨兽之城。',
        detailMarkdown: `### 城区划分\n市政中心、沃森区、太平洲、恶土荒漠。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-cy-5-${DEMO_TS}`,
        projectId,
        name: '赛博精神病',
        aliases: ['赛博崩溃症候群', 'Cyberpsychosis'],
        category: 'term',
        attributes: { 病症分类: '神经退行性异化', 诱发机制: '义体过载剥离人性' },
        relations: [],
        summary: '义体改造率过高导致的不可逆心理异化，患者会丧失同理心并陷入无差别狂暴屠杀。',
        detailMarkdown: `### 应对部队\n暴恐机动队（Max-Tac）负责现场物理清除。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-cy-6-${DEMO_TS}`,
        projectId,
        name: '强尼·银手',
        aliases: ['摇滚叛客', 'Johnny Silverhand'],
        category: 'character',
        attributes: { 身份定位: '传奇怪才黑客/摇滚乐手', 状态: '意识印记存储中' },
        relations: [
          { targetId: 'V', targetName: 'V', relationType: '共生寄生' },
          { targetId: '荒坂集团', targetName: '荒坂集团', relationType: '毕生宿敌' },
        ],
        summary: '曾用核弹炸毁荒坂大厦的传奇叛逆者，意识以生物芯片形式寄宿在主角脑海中。',
        detailMarkdown: `### 性格特征\n嘴硬心软，言辞刻薄，极具反叛精神与艺术狂热。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
    ],
  },

  // ── 3. 西方史诗剑与魔法 ──────────────────────────────────
  {
    id: 'epic-fantasy',
    title: '圣剑与龙王座 (西方奇幻)',
    subtitle: '圣堂骑士·龙语魔法·秘境遗迹·古神契约',
    genre: 'fantasy',
    badge: '西方奇幻',
    description: '包含亚瑟骑士王、梅林大魔导师、圣光教廷、圆桌骑士团、誓约胜利之剑、阿瓦隆圣地等史诗级全套世界观。',
    entitiesCount: 6,
    entities: (projectId: string): CodexEntity[] => [
      {
        id: `demo-fa-1-${DEMO_TS}`,
        projectId,
        name: '亚瑟·潘德拉贡',
        aliases: ['骑士王', '永恒之王', '选定者'],
        category: 'character',
        attributes: { 身份定位: '不列颠之王/圆桌领袖', 阶位: '传奇圣骑士', 契约古龙: '红龙血脉' },
        relations: [
          { targetId: '梅林', targetName: '梅林', relationType: '帝师导师' },
          { targetId: '誓约胜利之剑', targetName: '誓约胜利之剑', relationType: '佩剑' },
          { targetId: '卡美洛王国', targetName: '卡美洛王国', relationType: '统治者' },
        ],
        summary: '拔出石中剑的天命君王，恪守八大骑士美德，带领人类抵御幽冥深渊的入侵。',
        detailMarkdown: `### 史诗功绩\n一统十二行省，建立代表平等与正义的圆桌骑士制度。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-fa-2-${DEMO_TS}`,
        projectId,
        name: '梅林',
        aliases: ['大贤者', '星之魔导士', '阿瓦隆看守者'],
        category: 'character',
        attributes: { 身份定位: '宫廷首席大魔导师', 阶位: '半神法皇' },
        relations: [
          { targetId: '亚瑟·潘德拉贡', targetName: '亚瑟·潘德拉贡', relationType: '辅佐者' },
        ],
        summary: '洞悉过去与未来的梦魔混血大魔导，以星辰之力引导命运的轨迹。',
        detailMarkdown: `### 魔法派系\n原初符文法术、时间流溯、星界投影。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-fa-3-${DEMO_TS}`,
        projectId,
        name: '誓约胜利之剑',
        aliases: ['王者之剑', 'Excalibur', '湖中圣剑'],
        category: 'item',
        attributes: { 圣物等级: '神话级宝具', 锻造者: '湖中仙女', 光芒属性: '破晓圣光' },
        relations: [
          { targetId: '亚瑟·潘德拉贡', targetName: '亚瑟·潘德拉贡', relationType: '誓约持有' },
        ],
        summary: '汇聚星宿光辉的神圣之剑，出鞘时能释放斩断深渊巨龙鳞甲的耀世金芒。',
        detailMarkdown: `### 圣剑结界\n剑鞘【阿瓦隆】可令佩戴者伤口在圣光中瞬间愈合，不老不死。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-fa-4-${DEMO_TS}`,
        projectId,
        name: '卡美洛王国',
        aliases: ['白垩圣城', '圣王之国'],
        category: 'faction',
        attributes: { 势力评级: '人类第一帝国', 守护结界: '十二圆桌圣光屏障' },
        relations: [],
        summary: '矗立在圣白巨岩之上的史诗王都，象征着人类文明对抗蛮荒与黑夜的灯塔。',
        detailMarkdown: `### 核心机构\n圆桌议会、王立魔导院、银翼圣堂骑士团。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-fa-5-${DEMO_TS}`,
        projectId,
        name: '阿瓦隆秘境',
        aliases: ['理想乡', '精灵圣岛'],
        category: 'location',
        attributes: { 危险评级: '神圣不可侵犯', 入口: '常年隐匿于永恒迷雾中' },
        relations: [],
        summary: '永不凋零的黄金之乡，古神与湖中仙女栖息的彼岸圣地。',
        detailMarkdown: `### 特殊法则\n时间在此停滞，唯有怀揣无暇纯洁灵魂之人方可引渡靠岸。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
      {
        id: `demo-fa-6-${DEMO_TS}`,
        projectId,
        name: '龙语原初魔法',
        aliases: ['真名咏唱', '龙神言灵'],
        category: 'term',
        attributes: { 体系分类: '太古高位魔法', 发动条件: '需具备真龙血脉或契约印记' },
        relations: [],
        summary: '直接通过声音引动天地元素共鸣的最高阶言灵术式，无需冗长施法材料。',
        detailMarkdown: `### 代表禁咒\n【终焉灭世焰】：唤醒太古黑龙降临焚尽千里大地。`,
        createdAt: DEMO_TS,
        updatedAt: DEMO_TS,
      },
    ],
  },
]
